### ISSUE TITLE
When I import this and run it occurs an error.

### ISSUE THREAD

**Issue by ghost** [JPro-one/JPro-from-Jars#1]
![5](https://user-images.githubusercontent.com/45443554/82478666-dda9ad00-9aee-11ea-9534-93575d892a6e.PNG)

How can I solve this?

**Comment by ghost** [comment]
How to run this project?

**Comment by ghost** [comment]
Help

**Comment by ghost** [comment]
I tried lot of times . But, the result was same. How can I solve this?

**Comment by ghost** [comment]
I run this project in linux. But , the error was same.

**Comment by FlorianKirmaier** [comment]
Maybe the wrong JDK is configured?
I will update this project with the latest version of JPro gradle etc.

**Comment by FlorianKirmaier** [comment]
I've updated the project.

it should like the following:

<img width="1386" alt="Screenshot 2020-05-24 at 13 12 56" src="https://user-images.githubusercontent.com/6547435/82752782-c7d30b00-9dc0-11ea-8cc3-bf0f2130741b.png">

Make sure you are using JDK11, AdoptOpenJDK is preferred, check whether it works from terminal without an IDE.

**Comment by ghost** [comment]
![Screenshot_20200527-115653_Edge](https://user-images.githubusercontent.com/45443554/82985288-65247e00-a011-11ea-98b0-9c43af6a5278.jpg)

I tested in my android  device.  But , it not display the full app.
Why???

**Comment by FlorianKirmaier** [comment]
The app is optimized for Desktop - so it doesn't work good for mobile.
It's quite an old application.

**Comment by ghost** [comment]
https://github.com/JPro-one/JPro-from-Jars/issues/3#issuecomment-634448795

The same method was used in web cam sarxos https://github.com/sarxos/webcam-capture/tree/master/webcam-capture-examples/webcam-capture-javafx-fxml

How to stream web cam in jpro?

is it possible with this method https://github.com/sarxos/webcam-capture/tree/master/webcam-capture-examples/webcam-capture-javafx-fxml ?

This lib used to access web cams from USB port.

**Comment by FlorianKirmaier** [comment]
It's probably possible to use the WebCam from the server and put it's images to the scenegraph.
But you have to workout the details for yourself.

**Comment by ghost** [comment]
I have a video player app created in javafx.

Can I run this app with JPro-from-jar project?

**Comment by FlorianKirmaier** [comment]
Currently we don't support the standard JavaFX-Mediaplayer. It's part of our Roadmap.
If you have a commercial interest in it, please feel free to contact us directly.
Another typical solution is to implement a simple player based on "HTMLView".

**Comment by ghost** [comment]
How to contact?
