### ISSUE TITLE
How to set the loader gif in center of the screen ?

### ISSUE THREAD

**Issue by ghost** [JPro-one/JPro-from-Jars#13]
I changed the loader gif.
 But , the position of the loader is in the left corner of the  browser's screen.

**Comment by FlorianKirmaier** [comment]
Thank you for the bug-report! (Please use jpro-tickets for bug reports)
We've fixed the problem.
You can test the fix with the version `2019.2.6-SNAPSHOT`

**Comment by ghost** [comment]
Was `2019.2.6-SNAPSHOT` released?

**Comment by FlorianKirmaier** [comment]
2019.2.6-SNAPSHOT is available and basically represents the current state of the development of the next version. It will change over time, which is why it's not recommended for production. But it can be used to check whether specific bugs are fixed - like yours.
