### ISSUE TITLE
no main manifest attribute. 

### ISSUE THREAD

**Issue by ghost** [JPro-one/JPro-from-Jars#14]
When I run HelloJPro jar it comes `no main manifest attribute`

**Comment by parasuraam** [comment]
How to run the HelloJPro.jar  ?

**Comment by FlorianKirmaier** [comment]
Why would you want to do so? It's the same application as from https://github.com/JPro-one/HelloJPro.
You would have to mention the main-class in the java command and also manually add JavaFX to the cp. But that's something one usually wouldn't do.

**Comment by PradeepSimba** [comment]
I asked this because I also have a same type of jar like HelloJPro jar.

How  can I run this jar with JPro ?

**Comment by ghost** [comment]
I asked this because I also have a same type of jar like HelloJPro jar.

How  can I run this jar with JPro ?

**Comment by ghost** [comment]
Same error.

**Comment by FlorianKirmaier** [comment]
That's a general Java/JavaFX question which isn't really related to this project or JPro in general.

This plugin is useful for generating runnable applications: https://badass-runtime-plugin.beryx.org/releases/latest/
There are similar plugins for Maven.

In general, I wouldn't recommend running your application based on a (fat?) jar. You would have to collect all the dependencies of the original project and build the whole classpath in the java command. Or create a fat-jar which also isn't recommended.

**Comment by ghost** [comment]
@FlorianKirmaier 

Can you give more information?

**Comment by FlorianKirmaier** [comment]
Hm, it's a bit chaotic. Creating a release based on a jar is usually avoided.
There are different plugins for maven and gradle to create installers:
 * https://github.com/openjfx/javafx-gradle-plugin
 * https://github.com/openjfx/javafx-maven-plugin
 * https://badass-runtime-plugin.beryx.org/releases/latest/
These solutions also bundle the java-version into the installer - which fixes a lot of potential issues.
We usually use the "badass" plugin, but that's just our preference. Maybe we should add them to our HelloWorld projects ...

**Comment by parasuraam** [comment]
How to add The Badass Runtime Plugin in maven project ?

For gradle I added The Badass Runtime Plugin like this and it worked.

    plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.8'
    id 'org.beryx.runtime' version '1.8.1'
    }


    repositories {
    mavenCentral()
    }

    javafx {
    modules = ['javafx.controls']
    }

    application {
    mainClassName = "org.example.hellofx.Launcher"
    applicationName = 'hellofx'
    }

    runtime {
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    jpackage {
        // jpackageHome = '/usr/lib/jvm/jdk14'
        if(org.gradle.internal.os.OperatingSystem.current().windows) {
            installerType = 'msi'
            // imageOptions = ['--win-console']
            installerOptions = ['--win-per-user-install', '--win-dir-chooser', '--win-menu', '--win-shortcut']
        }
    }
    }


How can I add the BADASS Runtime Plugin  in  maven project ?

When I add BADASS Runtime Plugin  dependency it comes an error.


    
    <dependency>
    <groupId>gradle.plugin.org.beryx</groupId>
    <artifactId>badass-runtime-plugin</artifactId>
    <version>1.8.0</version>
    </dependency>

After adding this . It comes `Cannot resolve gradle.plugin.org.beryx:badass-runtime-plugin:1.8.0`

Can you give a sample pom.xml file for The Badass Runtime Plugin?


I want to add my jar with JPro.

I asked this because I also have a same type of jar like HelloJPro jar.

When I run my jar it comes an error?

Can you give a sample pom.xml file for The Badass Runtime Plugin?

**Comment by parasuraam** [comment]
The badass-runtime-plugin is only for Gradle. But , I am using maven. was there any plugin for maven like badass-runtime-plugin?

**Comment by ghost** [comment]
The badass-runtime-plugin is only for Gradle. But , I am using maven. was there any plugin for maven like badass-runtime-plugin?

**Comment by FlorianKirmaier** [comment]
* Sample Project (without plugin) + Tutorial: https://github.com/dlemmermann/JPackageScriptFX
* jlink+jpackager plugin for maven: https://github.com/agilhard-oss/jlink-jpackager-maven-plugin

Can't tell whether they are good.
