### ISSUE TITLE
Build failed with: java.io.IOException: invalid null character in command

### ISSUE THREAD

**Issue by ashokkumarvel** [JPro-one/JPro-from-Jars#16]
When I run my jar it come  like this

`07:55:06: Executing task 'jproRun'...

> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :prepareBrowser

> Task :jproRun
C:\Users\ashok\.gradle\daemon\6.4.1\RUNNING_PID already exists. Process with pid: 1208 is terminated. A new process is getting created.

> Task :jproRun FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jproRun'.
> java.io.IOException: invalid null character in command

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.4.1/userguide/command_line_interface.html#sec:command_line_warnings
2 actionable tasks: 2 executed
07:55:12: Task execution finished 'jproRun'.`

Give a solution for this.

**Comment by FlorianKirmaier** [comment]
Can you run it with --stracktrace and post the stacktrace? 
Which exact command are you using? 
Which OS are you using?

**Comment by ashokkumarvel** [comment]
Stracktrace https://github.com/JPro-one/JPro-from-Jars/issues/16#issue-651205308

I am using win 10.

**Comment by FlorianKirmaier** [comment]
I don't see a stacktrace in the comment. 
I only the the message of the Exception but not the exact stacktrace.
And which exact command are you executing? `./gradlew jpro:run`?

**Comment by FlorianKirmaier** [comment]
@ashokkumarvel 
If you've found the reason, it would help us for us to know, either to fix it/improve error message or for documentation purposes.
