### ISSUE TITLE
How to run two jars at same time with JPro-from-Jars?

### ISSUE THREAD

**Issue by ghost** [JPro-one/JPro-from-Jars#17]
I runned my project.  But , the game2048 jar only show in the browser .

I want to run two jar with two different ports in same server.

https://github.com/JPro-one/JPro-from-Jars/issues/12#issuecomment-652681208

I tried to run the game2048.jar and HelloJPro.jar. But , all fails.

How can I do this?

**Comment by raamipja** [comment]
Same issue.

I also have the same issue.

**Comment by FlorianKirmaier** [comment]
One JProServer can only run on a single port. But it might be possible to distribute it between different ports with a proxy, but that would be rather uncommon.
In the current sample, dependent whether you open hello.html or 2048.html a different application is opened.
If you want to open 2 programs you can also just start 2 servers which might be easier.
