### ISSUE TITLE
I run my jar. but , it not works.

### ISSUE THREAD

**Issue by ghost** [JPro-one/JPro-from-Jars#3]
I run my jar with jpro. but, it not works.

why this not works?

this  app is based on screen capture. .

can I use javacv with jpro ?

**Comment by poorvajappja** [comment]
After , I run JPro. The output was a blank white screen.

**Comment by poorvajappja** [comment]
My app is based on screen capture.

**Comment by poorvajappja** [comment]
![12](https://user-images.githubusercontent.com/65843311/82802554-b9f2b800-9e9c-11ea-93da-4aecb260bf35.PNG)

  
JPRO_VERSION=2019.2.3
MAINCLASS= screen.view.ScreenView


Output in browser:

white screen in browser like below

![111](https://user-images.githubusercontent.com/65843311/82802800-19e95e80-9e9d-11ea-9598-114fddd7cfc3.PNG)

**Comment by FlorianKirmaier** [comment]
Now clue how you expect anyone to be able to help you with the available information. I would suspect you did use run instead of jproRun.

**Comment by ghost** [comment]
No , I export the jar file . Then , I paste the jar into jpro folder.


my main classs.

JPRO_VERSION=2019.2.3
MAINCLASS= screen.view.ScreenView

After , I run JPro with this command: ./gradlew.bat jproRun.

**Comment by FlorianKirmaier** [comment]
Is ScreenView a JavaFX Application?
What is the output in the commandline?

**Comment by ghost** [comment]
Yes , It is a  JavaFX Application .

In command line :

`16:28:57: Executing task 'jproRun'...

Starting Gradle Daemon...
Gradle Daemon started in 28 s 747 ms
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :prepareBrowser

> Task :jproRun
C:\Users\prade\.gradle\daemon\6.4.1\RUNNING_PID already exists. Process with pid: 5444 is terminated. A new process is getting created.

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/C:/Users/prade/.gradle/caches/modules-2/files-2.1/com.google.inject/guice/4.1.0/eeb69005da379a10071aa4948c48d89250febb07/guice-4.1.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[info] a.e.s.Slf4jLogger - Slf4jLogger started
[info] c.jpro.activity - Starting the server
[info] c.j.i.s.Initializer$ -  *** Starting JPro: https://www.jpro.one/ ***
[info] c.j.i.s.Initializer$ - OS: Windows 10
[info] c.j.i.s.Initializer$ - JPro: 2019.2.3
[info] c.j.i.s.Initializer$ - Java version: 14
[info] c.j.i.s.Initializer$ - JVM: 14 Oracle Corporation
[info] c.j.i.s.Initializer$ - redirected OUT / ERR
[info] c.j.i.s.Initializer$ - installed SLF4JBridge
[info] c.j.i.s.MonocleInitializer$ - screen: null
Warning: Quantum will not submit render jobs, nothing should draw
[info] c.j.i.s.Initializer$ - finished init!
[info] c.j.i.s.Initializer$ - JavaFX version: 11.0.3.4-jpro+0-2019-12-20-085014
[info] c.j.i.c.m.DynamicDataModel - Started Monitoring chart data...
[info] c.j.i.c.m.ChartJSONImExporter - Imported chart data Mon May 25 16:30:53 IST 2020
[info] play.api.Play - Application started (Prod)
[info] p.c.s.AkkaHttpServer - Listening for HTTP on /[0:0:0:0:0:0:0:0]:8080
[info] c.jpro - application requested: 0!default
[info] c.jpro - Creating Application: 0!default
[info] c.jpro - remoteAddress 0:0:0:0:0:0:0:1
[info] c.jpro - host          localhost:8080
[info] c.jpro - uri           /app/0!default
[info] c.j.i.s.ViewSerializerActor - appdef: AppByMain(default,screen.view.ScreenView,None,NamedClassLoader(system),false) clientinfo: ClientInfo(http://localhost:8080/,http://localhost:8080/app/default,1536.0,754.0,false,en-GB,List(en-GB, en, en-US),Map(Idea-48d1b69c -> 70e0d499-4f9d-477b-a8d3-3a77c746d559))out: Actor[akka://application/system/StreamSupervisor-0/$$f-actorRefSource#-580585632]
[info] com.jpro.JS - received msg: new MainID: 63 userid: 666361456
`

**Comment by FlorianKirmaier** [comment]
You can set visible to true in the build.gradle file to see what's really happening.
You have to use the Stage provided by the start method of the application, otherwise it doesn't work.

**Comment by poorvajappja** [comment]
I set visible = true in build.gradle. Then I run the project. But, the jar file also like a blank screen.

when I run my jar without JPro it works perfectly .

But , why this not work with JPro ?

**Comment by poorvajappja** [comment]
My project [screenview.zip](https://github.com/JPro-one/JPro-from-Jars/files/4686742/screenview.zip)

jar file in the dist folder.

What I am doing wrong in this project ?

**Comment by ashokkumarvel** [comment]
I also have the same problem .

How can I solve this error ?

**Comment by FlorianKirmaier** [comment]
Hm, very interesting application for JPro.

I would recommend the following:
 - Add some other elements to the SceneGraph, maybe only the snapshots don't work for some reason
 - Maybe try lowering the frequency, how often the snapshots are created. the browser might need some time to show the image. If the image gets replaced as it's shown then you might not see anything.
 - Maybe the snapshots don't work for some reason? JPro tries to use "headless" configurations which might interfere with the awt robot somehow.

**Comment by FlorianKirmaier** [comment]
Be aware that JPro doesn't send the content of the application as a video stream.
JPro sends the whole scene graph to the client, which is pixel perfect etc. for normal application.
But when you are using it so send over many snapshots, then it's not very optimised. Every snapshot basically get's send to the client as a single image. By default, the images are even pixel perfect without lossy compression.

**Comment by PradeepSimba** [comment]
Can you give a solution for  screen shot ?
how can I access the web cams from jpro and stream ?

**Comment by ashokkumarvel** [comment]
Is video streaming not possible in jpro ?

Can you give solution for this?

**Comment by ghost** [comment]
Is video streaming not possible in jpro ?

Can you give solution for this?

**Comment by PradeepSimba** [comment]
https://github.com/JPro-one/JPro-from-Jars/issues/3#issuecomment-634448795

The same method was used in web cam sarxos https://github.com/sarxos/webcam-capture/tree/master/webcam-capture-examples/webcam-capture-javafx-fxml

How to stream web cam in jpro?

is it possible with this method https://github.com/sarxos/webcam-capture/tree/master/webcam-capture-examples/webcam-capture-javafx-fxml ?

This lib used to access web cams from USB port.

**Comment by ashokkumarvel** [comment]
I think video streaming not possible in JPro.

**Comment by FlorianKirmaier** [comment]
The method with using/replacing a lot of images should work, but it's just not working very well.

**Comment by ghost** [comment]
screen shot streaming is possible or not in JPro?

**Comment by ghost** [comment]
It is not possible with JPro.

**Comment by ashokkumarvel** [comment]
Yes , Video streaming is not possible in JPro.

you can go to webswing .  It works.

**Comment by ghost** [comment]
@FlorianKirmaier

 is it possible or not ?

is video streaming not possible in JPro?

**Comment by FlorianKirmaier** [comment]
as mentioned, sharing via screenshots should technically work, but it's not so performant.

**Comment by FlorianKirmaier** [comment]
I think the questions are now answered.

**Comment by FlorianKirmaier** [comment]
@poorvajappja @ashokkumarvel @PradeepSimba 
To clarify it, it would be technical possible to support WriteableImages in combination with Video Streaming. If that's commercially important to you, we can move it up in our roadmap and implement it for you.

**Comment by ashokkumarvel** [comment]
Video and Audio streaming is much important for website . But , JPro does not support video streaming . So , add the streaming feature in JPro .
