### ISSUE TITLE
Multi applications

### ISSUE THREAD

**Issue by Hugolarson** [JPro-one/JPro-from-Jars#5]
Hello,
Is it possible to use this concept to deploy several applications/jars in one JPro instance?
Every application has it's own main class in it's jar file.

**Comment by FlorianKirmaier** [comment]
Check out this part of the documentation on how to configure multiple applications: https://www.jpro.one/?page=docs/current/2.2/CONFIGURING_JPRO
Change the jpro.conf and add a statement like the following:
```
jpro.applications {
  "appname1" = package.Application1
  "appname2" = package.Application2
}
```

Then you have to add multiple index-file in the folder `src/main/resources/jpro/html/`

Be aware, that with this solution, all applications share the same classloader. This can lead to problems when the applications are using the same libraries with different versions.

**Comment by Hugolarson** [comment]
Please explain further.
How can the applications be in independent jar files with their own /resources/ folder?
Or does "appname1" and "appname2" be in same jar?

My goal is to have "appname1" and "appname2" in separate jars on same JPro instance.

**Comment by Hugolarson** [comment]
Please make a sample with two independent and runnable jar applications running on same JPro server.
Thanks.

**Comment by PradeepSimba** [comment]
@Hugolarson  

How to use multi applications?

https://github.com/JPro-one/JPro-from-Jars/issues/17#issue-656582296
