### ISSUE TITLE
How can I chane the title?

### ISSUE THREAD

**Issue by ghost** [JPro-one/JPro-from-Jars#6]
When I run it comes like this.
![title](https://user-images.githubusercontent.com/45443554/84591966-17f13a80-ae60-11ea-8185-db2b07130031.PNG)

How can I change the title of  web page?

**Comment by ashokkumarvel** [comment]
Give a solution.

**Comment by FlorianKirmaier** [comment]
add the file "src/main/resources/jpro/html/index.html" based on a copy of the original index.html file.
Then you can change the attributes of the jpro-tag to remove the loader or change the title in the index.html file.
