### ISSUE TITLE
How to remove loader in this project?

### ISSUE THREAD

**Issue by ashokkumarvel** [JPro-one/JPro-from-Jars#7]
I removed the loader with this https://github.com/JPro-one/JPro-tickets/issues/15#issuecomment-458121708

But, how can I do in this project?

**Comment by FlorianKirmaier** [comment]
add the file "src/main/resources/jpro/html/index.html" based on a copy of the original index.html file.
Then you can change the attributes of the jpro-tag to remove the loader or change the title in the index.html file.

**Comment by ashokkumarvel** [comment]
I want to remove the loader in JPro-from-jar project.

Can you give more information?

**Comment by FlorianKirmaier** [comment]
Which part did you not understand? Can you give me more information?

**Comment by ashokkumarvel** [comment]
My project structure
![pstr](https://user-images.githubusercontent.com/65845270/84725560-8e994f80-afa8-11ea-8454-f9ed5c61dac7.PNG)

I added this src/main/resources/jpro/html/index.html .

But , an error :


![error](https://user-images.githubusercontent.com/65845270/84725686-cdc7a080-afa8-11ea-805b-d06d4ec5453a.PNG)

I can't understand this?

help me !!!

How can I do this?

**Comment by ashokkumarvel** [comment]
index.html

![save](https://user-images.githubusercontent.com/65845270/84767725-8b29b680-aff0-11ea-9dc6-ab5205a05fd2.PNG)


My project structure .

![pstr](https://user-images.githubusercontent.com/65845270/84767757-95e44b80-aff0-11ea-9da9-d501c9279b32.PNG)


It occurs an error.


`[info] c.jpro - application requested: 0!undefined
[warn] c.jpro - The requested application "0!undefined" does not exist!
[info] c.jpro - application requested: 0!undefined
[warn] c.jpro - The requested application "0!undefined" does not exist!
[info] c.jpro - application requested: 0!undefined
[warn] c.jpro - The requested application "0!undefined" does not exist!
[info] c.jpro - application requested: 0!undefined
[warn] c.jpro - The requested application "0!undefined" does not exist!
[info] c.jpro - application requested: 0!undefined
[warn] c.jpro - The requested application "0!undefined" does not exist!`


How can I solve this?

**Comment by FlorianKirmaier** [comment]
The first screenshot only shows that the ide doesn't support modern HTML. You can ignore it.

The latest post looks good, but I think you've changed the href attribute? By default it should be href="/app/default". That's probably causing the error you've mentioned.

**Comment by ashokkumarvel** [comment]
https://github.com/JPro-one/JPro-tickets/issues/15#issuecomment-644122996


As you mentioned I did this . But , it not worked.

I want to add custom gif.

My project structure.

![project](https://user-images.githubusercontent.com/65845270/84860426-9cc09c00-b08c-11ea-8fb9-3e90cfccd95f.PNG)

index.html

![1](https://user-images.githubusercontent.com/65845270/84860457-afd36c00-b08c-11ea-86d3-43c7ffe551b7.PNG)

gradle.properties

JPRO_VERSION=2019.2.5
MAINCLASS=ab.Ab

Error :

`A problem occurred configuring root project 'JPro-from-Jars'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.sandec.jpro:jpro-plugin-gradle:2019.2.5.
     Searched in the following locations:
       - https://jcenter.bintray.com/com/sandec/jpro/jpro-plugin-gradle/2019.2.5/jpro-plugin-gradle-2019.2.5.pom
       - https://plugins.gradle.org/m2/com/sandec/jpro/jpro-plugin-gradle/2019.2.5/jpro-plugin-gradle-2019.2.5.pom
       - http://sandec.bintray.com/repo/com/sandec/jpro/jpro-plugin-gradle/2019.2.5/jpro-plugin-gradle-2019.2.5.pom
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

`

I want to add a custom gif. 

How to change this  version 2019.2.3-SNAPSHOT to  version 2019.2.5-SNAPSHOT and add custom gif ?

**Comment by FlorianKirmaier** [comment]
The JPRO_VERSION has to be `2019.2.5-SNAPSHOT` (with `-SNAPSHOT`). 2019.2.5 will be released in the future.
I've added a comment to the original ticket:
If you want to use your own loader, you should NOT set `loader="none"`. This will also disable your custom loader.
