### ISSUE TITLE
Bug report.

### ISSUE THREAD

**Issue by ashokkumarvel** [JPro-one/JPro-from-Jars#9]
App's UI

![e](https://user-images.githubusercontent.com/65845270/85200561-1ae3a380-b316-11ea-96a7-ee4218687115.PNG)

I tested this app  2 days ago . This app worked perfectly.

But , today I tested this. it comes a white screen. 

Then , I test my another app . the result was same.

help me!!!

Why it comes like this?

**Comment by FlorianKirmaier** [comment]
Best guess would be, that another not working server is running on the same port?
Try restarting your PC to free all relevant ports from hanging processes.

**Comment by ashokkumarvel** [comment]
I changed the port number. then , I runed the JPro  server. But , the output was a blank screen.

**Comment by FlorianKirmaier** [comment]
Hm, it works for me. It's probably something simple.
Im using Java11. Does it work when you checkout this project without any changes?
If the issue is based on your application, i would need a simple test-application.

**Comment by ashokkumarvel** [comment]
My project .

Jar file in dist folder.

[DEMO.zip](https://github.com/JPro-one/JPro-from-Jars/files/4808944/DEMO.zip)

**Comment by FlorianKirmaier** [comment]
Works for me. Did you change the mainclass in the file gradle.properties?

**Comment by ashokkumarvel** [comment]
Yes, I changed .

mainclass = demo.DEMO

**Comment by FlorianKirmaier** [comment]
What's the console output?
